Repository daniel-norris/neu_ui, pull requests merged in 2020-07, with the labels that each got.

#7 Changelog for v0.1.15-2 [skip ci]
  .circleci/config.yml
  package.json
Labels: enhancement, minor

#8 updated readme
  README.md
  src/components/buttons/Button.test.js
Labels: minor

#9 Latest stable version
  debug.log
Labels: minor

#10 Create LICENSE
  LICENSE
Labels: documentation, minor

#11 updated readme
  README.md
  debug.log
Labels: documentation, minor

#14 Typography component description updated
  src/components/typography/Typography.stories.mdx
Labels: documentation, skip-release
