Repository daniel-norris/neu_ui, pull requests merged in 2020-11, with the labels that each got.

#102 Add simple child test for ListItem component
  src/components/listGroup/ListItem.test.js
Labels: tests

#103 Add simple child test for ListGroup component
  src/components/listGroup/ListGroup.test.js
Labels: tests

#114 Issue#27: Created a nav component
  src/components/nav/Nav.js
  src/components/nav/Nav.stories.mdx
  src/components/nav/NavLink.js
  src/index.js
Labels: enhancement

#115 Added Marathi language
  translations/marathi/README.md
Labels: documentation
