Repository daniel-norris/neu_ui, pull requests merged in 2020-10, with the labels that each got.

#17 added title, icon and site meta data
  public/favicon.ico
  public/index.html
Labels: enhancement

#18 New typography component
  package-lock.json
  package.json
  src/components/buttons/Button.js
  src/components/buttons/Button.test.js
  src/components/typography/Typography.js
  src/components/typography/Typography.stories.mdx
  src/components/typography/Typography.test.js
Labels: enhancement

#28 Update documentation
  .gitignore
  CONTRIBUTING_GUIDE.md
  README.md
  debug.log
  src/ContributionGuide.mdx
  src/StartContributing.mdx
  src/components/forms/Toggle.js
  src/index.js
Labels: bug, documentation

#29 fix for storybook documentation
  .circleci/config.yml
  src/Contribution Guide.mdx
  src/Start Contributing.mdx
Labels: documentation

#30 fixed line break errors in contribution guide
  src/ContributionGuide.stories.mdx
  src/StartContributing.stories.mdx
Labels: documentation

#24 Fix issue where svg fill is wrong colour
  src/components/forms/Select.js
Labels: bug

#31 updated readme and contribution guidelines
  CONTRIBUTING_GUIDE.md
  debug.log
  src/components/forms/Select.js
Labels: documentation

#33 Fix circleci config
  .circleci/config.yml
Labels: bug

#35 updated readme
  README.md
Labels: documentation

#39 Add translation of the README into Brazilian Portuguese
  translations/portuguese/README.md
Labels: documentation

#45 Add link to translations
  README.md
Labels: documentation

#46 French translation. 2 Typos fixed
  README.md
  translations/french/readme.md
  translations/vietnamese/readme.md
Labels: documentation

#48 Added CardHeader test suite
  src/components/card/CardHeader.test.js
Labels: tests

#47 Fixed alignment issue with Radio buttons
  src/components/forms/Check.js
Labels: bug

#37 Translated English README.md into spanish
  translations/spanish/README.md
Labels: documentation

#51 Create a simple test for the Input component
  package-lock.json
  package.json
  src/components/forms/Input.test.js
Labels: tests

#60 Add unit test for CardText component according to #56
  src/components/card/CardText.test.js
Labels: tests

#61 chore: #55 add card subtitle test
  src/components/card/CardSubtitle.test.js
Labels: tests

#59 CardBody test added
  src/components/card/CardBody.test.js
Labels: tests

#58 Setup jest-dom to extend test functionalities + Button tests
  package-lock.json
  package.json
  src/components/buttons/Button.js
  src/components/buttons/Button.test.js
  src/setupTests.js
Labels: tests

#75 Improving Typography component test coverage to 97%.
  src/components/typography/Typography.test.js
Labels: tests

#62 chore: #57 add card img test
  src/components/card/CardImg.js
  src/components/card/CardImg.test.js
Labels: tests

#77 Add TextArea, Label, Select component test (#69, #66, #67)
  src/components/forms/Label.test.js
  src/components/forms/Select.test.js
  src/components/forms/TextArea.test.js
Labels: tests

#81 Add german Translation
  translations/german/README.md
Labels: documentation

#73 Translate CONTRIBUTING.md to portuguese
  translations/portuguese/CONTRIBUTING.md
  translations/portuguese/README.md
Labels: documentation

#82 Greek translation
  README.md
  translations/greek/README.md
Labels: documentation

#83 added test to progress component #71
  src/components/progress/Progress.test.js
Labels: tests

#84 Coverage check component
  src/components/forms/Check.test.js
Labels: tests

#85 Add Form Test
  src/components/forms/Form.test.js
Labels: tests

#89 Added polish translation of readme
  README.md
  translations/malay/README.md
  translations/polish/README.md
  translations/spanish/README.md
Labels: documentation

#91 Fix/87 button change cursor onhover
  src/components/buttons/Button.js
Labels: enhancement

#93 add initial test for FormGroup component
  src/components/forms/FormGroup.test.js
Labels: tests

#94 Add translation links
  README.md
  translations/french/README.md
  translations/german/README.md
  translations/vietnamese/README.md
Labels: documentation

#88 Added ListGroup Component.
  src/components/listGroup/ListGroup.js
  src/components/listGroup/ListGroup.stories.mdx
  src/components/listGroup/ListItem.js
Labels: enhancement

#95 Translate Contributing Guide and correct typos
  CONTRIBUTING_GUIDE.md
  translations/portuguese/CONTRIBUTING.md
  translations/portuguese/CONTRIBUTING_GUIDE.md
  translations/portuguese/README.md
Labels: documentation

#92 Refactor toggle component
  src/components/forms/Form.stories.mdx
  src/components/forms/Toggle.js
Labels: enhancement

#90 Recommit adding card title testing #54
  src/components/card/CardTitle.test.js
Labels: tests

#96 Greek translation of the CONTRIBUTING file
  translations/greek/CONTRIBUTING.md
  translations/greek/README.md
Labels: documentation

#97 Add tests for Toggle component
  src/components/forms/Toggle.test.js
Labels: minor, tests

#100 updated outdated dependencies
  package-lock.json
  package.json
  src/ContributionGuide.stories.mdx
Labels: minor

#105 updated readme with build status
  README.md
Labels: documentation
